function errorOnObsoleteSurfmSyntax(function_name,argcount)
% Errors appropriate to the syntaxes SURFM(Z), SURFACEM(Z),
% SURFM(Z,GRATSIZE), SURFACEM(Z,GRATSIZE), and PCOLORM(Z,GRATSIZE);
% but NOT PCOLORM(Z).

% Copyright 2008 The MathWorks, Inc.
% $Revision: 1.1.6.1 $  $Date: 2008/04/03 03:13:32 $

if argcount == 1
    error(['map:' function_name ':obsoleteSyntax1'], ...
        ['The syntax', ...
        '\n\n   %s(Z)\n\n', ...
        'made the implicit assumption of a perfect match between the', ...
        ' geographic\nlimits of the current map axes', ...
        ' and your data grid, and this syntax is\nno longer supported.' ...
        ' Instead, you need to pass the geographic limits\nof your data', ...
        ' to %s, like this:', ...
        '\n\n   %s(latlim, lonlim, Z)\n', ...
        '\nwhere LATLIM and LONLIM have the form:\n\n', ...
        '   LATLIM = [southern_limit northern_limit]\n', ...
        '   LONLIM = [western_limit  eastern_limit ]'], ...
        function_name, upper(function_name), function_name)
else
    error(['map:' function_name ':obsoleteSyntax2'], ...
        ['The syntax', ...
        '\n\n   %s(Z, gratsize)\n\n', ...
        'made the implicit assumption of a perfect match between the', ...
        ' geographic\nlimits of the current map axes', ...
        ' and your data grid, and this syntax is\nno longer supported.' ...
        ' Instead, you need to call MESHGRAT before calling\n%s,', ...
        ' like this:', ...
        '\n\n   [lat, lon] = meshgrat(latlim, lonlim, gratsize);', ...
        '\n   %s(lat, lon, Z)\n', ...
        '\nwhere LATLIM and LONLIM express the geographic limits of', ...
        ' your data\nand have the form:\n\n', ...
        '   LATLIM = [southern_limit northern_limit]\n', ...
        '   LONLIM = [western_limit  eastern_limit ]'], ...
        function_name, upper(function_name), function_name)
end
