function warnObsoleteMSGSyntax(func_name)

% Copyright 2007 The MathWorks, Inc.
% $Revision: 1.1.6.1 $  $Date: 2007/11/09 20:29:49 $

warning(['map:' func_name ':obsoleteMSGSyntax'],...
    ['Function %s no longer returns error message strings in \noutput argument MSG.' ...
    ' Instead any errors are thrown where they occur. \nYou should remove the last' ...
    ' output argument (MSG) from your call to \n%s in order to avoid this warning.' ...
    ' If you want to handle errors \nyourself, call %s in a try-catch block.'], ...
    upper(func_name),upper(func_name),upper(func_name))
