function R = constructGeoRasterReference( ...
    rasterSize, rasterInterpretation, angleUnits, ...
    firstCornerLat, firstCornerLon, ...
    deltaLatNumerator, deltaLatDenominator, ...
    deltaLonNumerator, deltaLonDenominator)
% Invoke the spatialref.GeoRasterReference constructor directly, catch
% any errors that are thrown, and issue a new error to provide a
% user-oriented explanation of what went wrong.

% Copyright 2010 The MathWorks, Inc.
% $Revision: 1.1.6.1 $  $Date: 2010/10/11 14:47:39 $

try
    % Individually, we expect the inputs to the GeoRasterReference
    % constructor to be valid, but in combination they might imply
    % out-of-range latitude or longitude limits.
    R = spatialref.GeoRasterReference( ...
        rasterSize, rasterInterpretation, angleUnits, ...
        firstCornerLat, firstCornerLon, ...
        deltaLatNumerator, deltaLatDenominator, ...
        deltaLonNumerator, deltaLonDenominator);
catch e
    % Indicate that invalid or inconsistent defining parameters have
    % been encountered through a user-oriented error message that avoids
    % exposing hidden properties of the GeoRasterReference class.
    switch(e.identifier)
        case 'map:spatialref:invalidLatProps'
            error('map:convertspatialref:invalidLatProps', ...
                ['In combination with the number of rows in the', ...
                ' raster grid, %d, the input referencing vector', ...
                ' or matrix implies latitude limits that extend', ...
                ' outside the interval [-90 90] degrees.'], ...
                rasterSize(1));
        % case 'map:spatialref:invalidLonProps'
        %     error('map:convertspatialref:invalidLonProps', ...
        %         ['In combination with the number of columns in the', ...
        %         ' raster grid, %d, the input referencing vector', ...
        %         ' or matrix implies longitude limits that cover', ...
        %         ' an interval wider than 360 degrees.'], ...
        %         rasterSize(2));
        otherwise
            throwAsCaller(e)
    end
end
