function h = render(this,layerName,legend,ax,visibility) %#ok<INUSL>
%RENDER Render the GriddedComponent.
% 
%   H = RENDER(LAYERNAME,LEGEND,AX,VISIBILITY) constructs a surface in
%   the axes AX, with the specified VISIBILITY. Input LEGEND is ignored
%   for this type of component.

%   Copyright 1996-2008 The MathWorks, Inc.
%   $Revision: 1.1.6.4 $  $Date: 2008/11/24 14:59:39 $

R = this.ReferenceMatrix;

if (~isempty(R))
  [this.Xdata, this.Ydata] = pixcenters(R,size(this.GriddedData));  
end

prevClim = get(ax,'CLim');
if strcmpi(this.DisplayType,'mesh')
    fc = get(ax,'Color');
    h = surface( ...
        'Parent',ax,...
        'Xdata',this.Xdata,...
        'Ydata',this.Ydata,...
        'Zdata',zeros(size(this.GriddedData)),...
        'Cdata',this.GriddedData,...
        'CDataMapping','scaled',...
        'FaceColor',fc...
        );
else
    h = surface(...
        'Parent',ax,...
        'Xdata',this.Xdata,...
        'Ydata',this.Ydata,...
        'Zdata',zeros(size(this.GriddedData)),...
        'Cdata',this.GriddedData,...
        'CDataMapping','scaled',...
        'EdgeColor','none',...
        'FaceColor','flat'...
        );
end

fig = ancestor(ax,'Figure');
ch = findall(ax,'Type','surface');
cmap = this.ColorMap;
clim = [min(this.GriddedData(:)) max(this.GriddedData(:))];

if length(ch) > 1
  clim = [min([prevClim, clim]) max([prevClim, clim])];
  cmap = demcmap(clim);
end

set(fig,'Colormap',cmap);
set(ax,'CLim',clim);  
set(h,'Visible',visibility,'Tag',layerName)
